// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8WjjX486hQAOv_u2ekDjx199XDPueKHY',
    appId: '1:762469910096:web:bf9f7036ad68ebc7b4b355',
    messagingSenderId: '762469910096',
    projectId: 'hey-ae396',
    authDomain: 'hey-ae396.firebaseapp.com',
    storageBucket: 'hey-ae396.appspot.com',
    measurementId: 'G-J3KZHL3E2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYxCf4mvD86bFygIIsGFA0Nf_4Yhnm1BU',
    appId: '1:762469910096:android:ca3f9b5a1629e53bb4b355',
    messagingSenderId: '762469910096',
    projectId: 'hey-ae396',
    storageBucket: 'hey-ae396.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEDHigBK2kwUkEgwGCmWV0XzBv341z804',
    appId: '1:762469910096:ios:4f78ee1623c633a4b4b355',
    messagingSenderId: '762469910096',
    projectId: 'hey-ae396',
    storageBucket: 'hey-ae396.appspot.com',
    iosBundleId: 'com.example.hey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEDHigBK2kwUkEgwGCmWV0XzBv341z804',
    appId: '1:762469910096:ios:4f78ee1623c633a4b4b355',
    messagingSenderId: '762469910096',
    projectId: 'hey-ae396',
    storageBucket: 'hey-ae396.appspot.com',
    iosBundleId: 'com.example.hey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8WjjX486hQAOv_u2ekDjx199XDPueKHY',
    appId: '1:762469910096:web:56de63b38655ca88b4b355',
    messagingSenderId: '762469910096',
    projectId: 'hey-ae396',
    authDomain: 'hey-ae396.firebaseapp.com',
    storageBucket: 'hey-ae396.appspot.com',
    measurementId: 'G-ZJHXLWSWNK',
  );
}
